"""fix spell word

Revision ID: 8049edcc288b
Revises: 798a274df841
Create Date: 2026-02-17 20:46:27.231175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8049edcc288b'
down_revision: Union[str, Sequence[str], None] = '798a274df841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', sa.JSON(), nullable=False))
    op.drop_column('user', 'settigns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settigns', sqlite.JSON(), nullable=False))
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
