"""add model

Revision ID: d08abbd01054
Revises: 4a54002fa7dc
Create Date: 2026-02-18 13:54:31.608730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd08abbd01054'
down_revision: Union[str, Sequence[str], None] = '4a54002fa7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('reminders', sa.JSON(), nullable=True))
    op.drop_column('medications', 'reminder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('reminder', sqlite.JSON(), nullable=True))
    op.drop_column('medications', 'reminders')
    # ### end Alembic commands ###
