"""Add pressure table

Revision ID: d2ac0cb035cc
Revises: b2445ae23545
Create Date: 2026-02-10 11:50:33.408399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ac0cb035cc'
down_revision: Union[str, Sequence[str], None] = 'b2445ae23545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pressure_measurement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('systolic', sa.Integer(), nullable=False),
    sa.Column('diastolic', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pressure_measurement')
    # ### end Alembic commands ###
