"""change systolic and diastolic names

Revision ID: f508665c1aa2
Revises: d2ac0cb035cc
Create Date: 2026-02-15 17:37:42.294758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f508665c1aa2'
down_revision: Union[str, Sequence[str], None] = 'd2ac0cb035cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pressure_measurement', sa.Column('sys', sa.Integer(), nullable=False))
    op.add_column('pressure_measurement', sa.Column('dia', sa.Integer(), nullable=False))
    op.drop_column('pressure_measurement', 'systolic')
    op.drop_column('pressure_measurement', 'diastolic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pressure_measurement', sa.Column('diastolic', sa.INTEGER(), nullable=False))
    op.add_column('pressure_measurement', sa.Column('systolic', sa.INTEGER(), nullable=False))
    op.drop_column('pressure_measurement', 'dia')
    op.drop_column('pressure_measurement', 'sys')
    # ### end Alembic commands ###
